package:
  name: rust_matchspec
  version: 0.2.2

source:
  path: ../

build:
  number: 0
  skip: true  #[py<37]

requirements:
  build:
    - {{ compiler('rust') }}  # [not win]
    - rust_win-64             # [win]
  host:
    - python
    - pip
    - maturin >=14.0,<15.0
  run:
    - python

test:
  imports:
    - rust_matchspec
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/remkade/matchspec
  doc_url: https://github.com/remkade/matchspec
  dev_url: https://github.com/remkade/matchspec
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A conda matchspec written in Rust
  description: |
    A Conda MatchSpec implementation in pure Rust.
    This allows you to parse a matchspec and validate it against a package to see if it matches.
