[build-system]
build-backend = "maturin"
requires = ["maturin<=0.13,<0.14"]

[project]
name = "rust_matchspec"
version = "0.1.0"
description = "A conda matchspec written in Rust"
requires-python = ">=3.7"

[tool.maturin]
features = ["python"]
python-source = "python"